#!/bin/bash

# Script to generate sample network trace files for Pensieve

echo "Generating sample network traces..."

# Create directories if they don't exist
mkdir -p cooked_traces
mkdir -p sim/cooked_traces
mkdir -p sim/cooked_test_traces
mkdir -p test/cooked_test_traces

# Generate synthetic traces using the existing script
cd sim
if [ -f "synthetic_traces.py" ]; then
    echo "Running synthetic_traces.py to generate sample traces..."
    python3 synthetic_traces.py
    
    # Copy generated traces to other directories
    if [ -d "cooked_traces" ] && [ "$(ls -A cooked_traces 2>/dev/null)" ]; then
        echo "Copying traces to other directories..."
        cp cooked_traces/* ../cooked_traces/ 2>/dev/null || true
        cp cooked_traces/* cooked_test_traces/ 2>/dev/null || true
        cp cooked_traces/* ../test/cooked_test_traces/ 2>/dev/null || true
        echo "Sample traces generated and copied successfully!"
    else
        echo "Warning: No traces were generated by synthetic_traces.py"
    fi
else
    echo "synthetic_traces.py not found. Creating simple sample trace manually..."
    
    # Create a simple sample trace file (format: time bandwidth)
    # This is a simple constant bandwidth trace
    cat > ../cooked_traces/sample_trace << EOF
0.5 5.0
1.0 5.0
1.5 5.0
2.0 5.0
2.5 5.0
3.0 5.0
3.5 5.0
4.0 5.0
4.5 5.0
5.0 5.0
EOF
    
    # Copy to other directories
    cp ../cooked_traces/sample_trace sim/cooked_traces/
    cp ../cooked_traces/sample_trace sim/cooked_test_traces/
    cp ../cooked_traces/sample_trace test/cooked_test_traces/
    
    echo "Simple sample trace created!"
fi

cd ..

echo ""
echo "Trace files status:"
echo "  cooked_traces/: $(ls -1 cooked_traces 2>/dev/null | wc -l) files"
echo "  sim/cooked_traces/: $(ls -1 sim/cooked_traces 2>/dev/null | wc -l) files"
echo "  sim/cooked_test_traces/: $(ls -1 sim/cooked_test_traces 2>/dev/null | wc -l) files"
echo "  test/cooked_test_traces/: $(ls -1 test/cooked_test_traces 2>/dev/null | wc -l) files"
echo ""
echo "Done!"
